export const ROOT = '/'
export const SIGN_IN = '/signin'
export const BALANCES = '/balances'
export const BALANCES_CREATE = '/balances/create'
export const NOT_FOUND_404 = '/404'
export const ERROR_500 = '/oops-500'
